spring:
  application:
    name: commandes-service

server:
  port: 9002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info

# Configuration base de données
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_commandes?createDatabaseIfNotExist=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

# Propriété demandée dans le sujet : nombre de jours pour les dernières commandes
mes-config-ms-commandes-last: 10
