spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: produits-service
          uri: lb://produits-service
          predicates:
            - Path=/produits/**
        - id: commandes-service
          uri: lb://commandes-service
          predicates:
            - Path=/commandes/**
        - id: interface-service
          uri: lb://interface-service
          predicates:
            - Path=/front/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
